# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c39deacf5bd53babfd22e99894cce6ffb5cb044e15a2ccb2812d172e905df171f4b56a1feda4380d024ce857ec2fdb7bef5b1f65fe6fafdb68869f6b6f70740

test:
  secret_key_base: 53cf0e81ee43bc5d36af1f3fe15b0e647b4c68a44130280b82e538e17ab9a745360eb4846266df90b3d623ac2c2636200d5a18d1d91c5f43e6895973f9d17d55

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
