# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23740e31d4e25cefcfa99dc2a7242d0b6b07f5501dbd2f322691e86927b16d7fdacf9bb1d2ea5392a895383a8a7522ec3ff9baed45bfcc57891d89caabdcda94

test:
  secret_key_base: cb2f98bcb74827fd3aefefb385c0d353024c3c8007c93ea789c43912cd42d9d0b3c0a44a65072feec0e3c8d53474c6c09e3d031213697eb94cc6bdb07843a5b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
