# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eccfa2c099f87305b02c1a6437a805b45f375bdd0514e392d0f9c9f8866e06437f3188b2e8c600263608edce3b47dd78880d67127ed9f62ce204bbde584994c1

test:
  secret_key_base: 85e9629c2e7c5ff04c26996b37de4cbf6f621d92d1e285c3566d7e0872d77ac869fbb0987471bd3c2ee3bc19224cbe4351f63c6c67439673366a8a6b7cf1205f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
